### PR TITLE
Warn on unexpected successes instead of failure

### LINKED ISSUE #48: Test suite fails when seed does not produce a counterexample
In [this build](https://hercules-ci.com/accounts/github/hercules-ci/derivations/%2Fnix%2Fstore%2Flw12sq8bmyab2mh68fylldc3dhbl690r-selective-0.4.2.drv/log?via-job=a6105d19-7638-4e94-a4aa-13a1d6e716d9) (look for "previous attempt"), the test suite fails and logs:

```
        Use --quickcheck-replay=116302 to reproduce. (expected failure)
       Interchange: (x *> (y <*? z)) == ((x *> y) <*? z):                                                                    OK (unexpected)
         +++ OK, passed 100 tests.
          (unexpected success)
         Use -p '/Validation.Theorems.Interchange: (x *> (y <*? z)) == ((x *> y) <*? z)/' to rerun this test only.
```

This is `theorem6` in `validationTheorems :: Tests`, which is an `expectFailure` test. This means that it is using a property test to find a counterexample for the interchange theorem. If it fails to find one, it fails the test suite.

Failing the test suite doesn't seem like the right thing to do here, because the absence of such a property can hardly be a requirement for the library to function correctly.

### PR DESCRIPTION
**Pull request by snowleopard**
Fixes #48.

### CODE REVIEW

File: test/Test.hs [hunk 1]
```diff
@@ -26,14 +25,14 @@ runTest labels (Test name expect property) = do
...
     result <- quickCheckWithResult (stdArgs { chatty = False }) property
     case (expect, isSuccess result) of
-        (ExpectSuccess, True)  -> putStrLn $ "OK: " ++ label
-        (ExpectFailure, False) -> putStrLn $ "OK (expected failure): " ++ label
+        (ExpectSuccess, True) ->
+            putStrLn $ "[OK] " ++ label
+        (ExpectFailure, False) ->
+            putStrLn $ "[OK, expected failure] " ++ label
+        (ExpectFailure, True) ->
+            putStrLn $ "[Warning, unexpected success] " ++ label
```
Comment (roberth) [inline test/Test.hs:33]: Someone unfamiliar with this test runner may rely on this to fail.

You could add a `UncheckedCounterexample` constructor to `Expect`, to hint to the reader that it's not suitable for checking that something is always `False`. You can also print a more informative message when it happens.

Comment (roberth) [inline test/Test.hs:33]: Someone unfamiliar with this test runner may rely on this to fail.

You could add a `UncheckedCounterexample` constructor to `Expect`, to hint to the reader that it's not suitable for checking that something is always `False`. You can also print a more informative message when it happens.

Comment (snowleopard) [reply test/Test.hs:33]: It's a very simplistic test runner indeed. It wasn't my intention to grow it into something more sophisticated but I'm happy to review a PR if you'd like to tweak things.
